descriptor-schema-version: "2.7"

info:
  name: "ida_platform"
  description: "IDA Platfrom with APIs"
  version: "6.9.420"
  author-link: "nattapon.p@eruditetech.net"
  author-name: "Nattapon Prasatthong"

app:
  cpuarch: "aarch64"
  type: "docker"
  resources:
    profile: exclusive
    network:
      -
        interface-name: eth0
        ports:
          tcp: ["6969"]

  startup:
    rootfs: rootfs.tar
    target: ["python","/modbus_ida/app.py"]
